### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


### Відповідь завдання 1:

In [196]:
import numpy as np
import random
vector = np.random.rand(10)
print(vector, '\nРозмір вектора  ', vector.shape)

matrix = np.array([[11,14, 17],
                   [20, 23, 26],
                    [29, 32, 35]])
print('\n', matrix, '\nРозмір матриці ', matrix.shape)

[0.29863982 0.11797703 0.85746353 0.69909613 0.94414687 0.96080516
 0.84240253 0.89577905 0.57944431 0.53304756] 
Розмір вектора   (10,)

 [[11 14 17]
 [20 23 26]
 [29 32 35]] 
Розмір матриці  (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


### Відповідь завдання 2:

In [197]:
# 1
vector = np.round(vector + 10, 2)
print(vector)

[10.3  10.12 10.86 10.7  10.94 10.96 10.84 10.9  10.58 10.53]


In [198]:
# 2
matrix = matrix * 2
print(matrix)

[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [199]:
# 3
vector = vector ** 2
print(vector)

[106.09   102.4144 117.9396 114.49   119.6836 120.1216 117.5056 118.81
 111.9364 110.8809]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [200]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

### Відповідь завдання 3:

In [201]:
# 1
result_matrix = np.dot(B, A)
print('Результирующая матрица result_matrix розмірністю', result_matrix.shape, '\n',  result_matrix)

Результирующая матрица result_matrix розмірністю (2, 2) 
 [[0.7281 0.5202]
 [0.2034 0.2846]]


In [202]:
# 2 чекаємо вектор розмірністю 2*1
result_matrix_C = np.dot(result_matrix, C)
print('Результирующая матрица result_matrix помножена на вектор С\n', result_matrix_C)

Результирующая матрица result_matrix помножена на вектор С
 [[0.5202]
 [0.2846]]


In [203]:
# 3 чекаємо матрицю розмірністю 2*2
result_matrix_D = np.dot(result_matrix, D)
print('Результирующая матрица result_matrix помножена на матрицю D\n', result_matrix_D)

Результирующая матрица result_matrix помножена на матрицю D
 [[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




### Відповідь завдання 4:

In [204]:
# 1
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [205]:
# 2
print(vector, vector.shape)
print(vector.T,  vector.shape)

[106.09   102.4144 117.9396 114.49   119.6836 120.1216 117.5056 118.81
 111.9364 110.8809] (10,)
[106.09   102.4144 117.9396 114.49   119.6836 120.1216 117.5056 118.81
 111.9364 110.8809] (10,)


Після транспонування змін не відбулося

In [211]:
# 3
column_vector = np.expand_dims(vector, axis=1)
print('Початковий вектор\n', vector, vector.shape)
print('Перетворений вектор\n', column_vector, column_vector.shape)

Початковий вектор
 [106.09   102.4144 117.9396 114.49   119.6836 120.1216 117.5056 118.81
 111.9364 110.8809] (10,)
Перетворений вектор
 [[106.09  ]
 [102.4144]
 [117.9396]
 [114.49  ]
 [119.6836]
 [120.1216]
 [117.5056]
 [118.81  ]
 [111.9364]
 [110.8809]] (10, 1)


Функцією expand_dims додали вимір і вектор перетворився на матрицю з одним стовпцем

In [216]:
# 4
column_vector_trans = column_vector.T
print('Перетворений вектор у транспонованому вигляді\n', column_vector_trans, column_vector_trans.shape)

Перетворений вектор у транспонованому вигляді
 [[106.09   102.4144 117.9396 114.49   119.6836 120.1216 117.5056 118.81
  111.9364 110.8809]] (1, 10)


Після перетворення вектора на матрицю він транспонується як матриця - зі стовпця транспонувався у однорядкову матрицю. 