В цьому домашньому завданні ми реалізуємо логістичну регресію на `numpy`.
Ці завдання допоможуть вам ґрунтовно засвоїти основні концепції логістичної регресії та реалізувати їх на практиці 🔥

#### Завдання 1: Реалізація функції сигмоїди
1. З використанням `numpy` напишіть функцію `sigmoid(z)` для обчислення значення сигмоїди згідно з формулою:
   $$
   \sigma(z) = \frac{1}{1 + e^{-z}}
   $$
2. Використовуючи цю функцію, обчисліть значення сигмоїди для наступних даних: $ z = [-2, -1, 0, 1, 2] $. Виведіть результат обчислень.


**Відповідь 1**

In [51]:
import numpy as np

# 1
def sigmoid(z):
    sigma = 1 / (1 + np.exp(-z))
    return sigma

# 2
z = np.array([-2, -1, 0, 1, 2])
print('Результати обчислень: ', sigmoid(z))

Результати обчислень:  [0.11920292 0.26894142 0.5        0.73105858 0.88079708]




#### Завдання 2: Реалізація функції гіпотези для логістичної регресії
1. Напишіть функцію `hypothesis(theta, X)`, яка обчислює гіпотезу для логістичної регресії, використовуючи функцію сигмоїди. Формула гіпотези:
   $$
   h_\theta(x) = \sigma(\theta^T x) = \frac{1}{1 + e^{-\theta^T x}}
   $$
2. Використайте функцію `hypothesis` для обчислення значень гіпотези для наступних даних:
   
   $\theta = [0.5, -0.5]$
   
   $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  Виведіть результат обчислень.


**Відповідь 2**

In [34]:
def hypotesis(theta, X):
    z = np.dot(X, theta.T)
    result = sigmoid(z)
    return result

In [35]:
theta = np.array([[0.5, -0.5]])
X = np.array([[1, 2], [1, -1], [1, 0], [1, 1]])
h = hypotesis(theta, X)
print(X, X.shape)
print(theta, theta.T.shape, '\n')
print('Результат обчислень значень гіпотези:\n', h)

[[ 1  2]
 [ 1 -1]
 [ 1  0]
 [ 1  1]] (4, 2)
[[ 0.5 -0.5]] (2, 1) 

Результат обчислень значень гіпотези:
 [[0.37754067]
 [0.73105858]
 [0.62245933]
 [0.5       ]]


#### Завдання 3: Реалізація функції для підрахунку градієнтів фукнції втрат
1. Напишіть функцію `compute_gradient(theta, X, y)`, яка обчислює градієнти функції втрат для логістичної регресії. Формула для обчислення градієнта:
   $$
   \frac{\partial L(\theta)}{\partial \theta_j} = \frac{1}{m} \sum_{i=1}^{m} \left[ (h_\theta(x^{(i)}) - y^{(i)}) x_j^{(i)} \right]
   $$
2. Використайте функцію `compute_gradient` для обчислення градієнтів для наступних даних:

  $\theta = [0.5, -0.5]$

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Виведіть результат обчислень.

**Відповідь 3**

In [45]:
theta = np.array([[0.5, -0.5]])
X = np.array([[1, 2], [1, -1], [1, 0], [1, 1]])
y = np.array([1, 0, 1, 0])
m = X.shape[0]


def compute_gradient(theta, X, y):
    h = hypotesis(theta, X)
    gradient = np.array([])
    for j  in range(theta.shape[1]):
        sum_err = 0.00
        for i in range(m):
            err = (h[i] - y[i]) * X[i, j]
            sum_err += err
            #print(err, sum_err)
        gradient_init = 1 / m * sum_err
        gradient = np.append(gradient, gradient_init)
    print('Результат обчислення градієнтів: ', gradient)
    return

compute_gradient(theta, X, y)


Результат обчислення градієнтів:  [ 0.05776464 -0.36899431]



#### Завдання 4: Реалізація повного батч градієнтного спуску

**Задача:**
1. 

   - Гіпотеза: $ h_\theta(x) = \sigma(\theta^T x) $
   - Оновлення параметрів: $ \theta_j := \theta_j - \alpha \frac{\partial L(\theta)}{\partial \theta_j} $
2. Використайте функцію `full_batch_gradient_descent` для обчислення параметрів моделі на наступних даних:

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Увага! Матриця $X$ вже має стовпець одиниць і передбачається, що це. - стовпець для intercept - параметра зсуву.

  Виведіть результат обчислень.


**Відповідь 4**

In [50]:
X = np.array([[1, 2], [1, -1], [1, 0], [1, 1]])
y = np.array([1, 0, 1, 0])

def full_batch_gradient_descent(X, y, lr=0.1, epochs=100):
    m, b = 0.0, 0.0  # Початкові параметри
    n = len(y)
    errors = []
    for _ in range(epochs):
        y_pred = m * X[:, 1] + b
        error = y_pred - y
        m_gradient = (2/n) * np.dot(error, X[:, 1])
        b_gradient = (2/n) * np.sum(error)
        # print(m_gradient, b_gradient)
        m -= lr * m_gradient
        b -= lr * b_gradient
        errors.append(np.sum(np.square(error)))
    return m, b, errors    

m, b, errors = full_batch_gradient_descent(X, y, lr=0.1, epochs=100)
m, b


(np.float64(0.20000004294005663), np.float64(0.39999993052152893))

#### Завдання 5. Обчислення точності моделі

1. Напишіть функцію `predict_proba(theta, X)`, яка використовує знайдені параметри $\theta$ для обчислення ймовірностей належності поточного прикладу з даних до класу $y=1$ на основі значень $\sigma(\theta^T x)$.

2. Напишіть функцію `predict(theta, X, threshold=0.5)`, яка обчислює клас з передбаченої імовірності належності екземпляра до класу 1 з порогом 0.5. Тобто якщо ймовірність менше 0.5, то передбачаємо клас 0, інакше клас 1.

3. Напишіть функцію `accuracy(y_true, y_pred)`, яка обчислює точність моделі, визначивши частку правильно передбачених класів.

  Формула метрики Accuracy:
  $$
  \text{Accuracy} = \frac{\sum_{i=1}^{m} I(\hat{{y}^{(i)}} = y^{(i)})}{m}
  $$

  де $\hat{{y}^{(i)}}$ - передбачене значення класу, $I$ - індикаторна функція (яка дорівнює 1, якщо умова виконується, і 0 - якщо ні), $m$ - кількість прикладів.

4. Обчисліть з використанням даних в завданні 4 $X$, $y$ та обчислених коефіцієнтах $\theta$ та виведіть на екран:
  - передбачені моделлю імовірності належності кожного з екземплярів в матриці `X` до класу 1
  - класи кожного екземпляра з матриці `X`
  - точність моделі.

**Відповідь 5**

In [140]:
# 5.1
def predict_proba(theta, X):
    z = X @ theta.T
    P = 1 / (1 + np.exp(-z))
    return P

X = np.array([[1, 2], [1, -1], [1, 0], [1, 1]])
theta = np.array([[m,b]])
predict_proba(theta, X)

array([[0.73105856],
       [0.45016603],
       [0.54983401],
       [0.6456563 ]])

In [ ]:
# 5.2


def predict(theta, X, threshold=0.5):
    z = X @ theta.T
    P = 1 / (1 + np.exp(-z))
    y_pred = np.array([], dtype=np.int8)
    for i in range(P.shape[0]):
        if P[i] >= threshold:
            y_pred = np.append(y_pred, 1)
        else:
            y_pred = np.append(y_pred, 0)
    #print(y_pred)
    return y_pred

predict(theta, X, 0.5)


array([1, 0, 1, 1])

In [212]:
# 5.3
def accuracy(y_true, y_pred):
    sum = 0
    y_pred = predict(theta, X, threshold=0.5)
    for i in range(len(y_pred)):
        if y_pred[i] - y_true[i] == 0:
            sum += 1
    accuracy = sum / len(y_pred)
    return accuracy

accuracy(y, y_pred)

0.75

In [221]:
# 5.4
'''Обчисліть з використанням даних в завданні 4 $X$, $y$ та обчислених коефіцієнтах $\theta$ та виведіть на екран:
  - передбачені моделлю імовірності належності кожного з екземплярів в матриці `X` до класу 1
  - класи кожного екземпляра з матриці `X`
  - точність моделі.'''

print(f'Розраховані моделлю імовірності належості єлемемнтів матриці Х до класу 1:\n {predict_proba(theta, X)}')
print(f'Класи кожного елементу матриці Х:\n {predict(theta, X, 0.5)}')
print(f'Точність моделі складає {accuracy(y, y_pred)}')

Розраховані моделлю імовірності належості єлемемнтів матриці Х до класу 1:
 [[0.73105856]
 [0.45016603]
 [0.54983401]
 [0.6456563 ]]
Класи кожного елементу матриці Х:
 [1 0 1 1]
Точність моделі складає 0.75
